---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(ggbeeswarm)


rm(list=ls())
setwd("~/Library/CloudStorage/Box-Box/SerologyR01/Jiangsu")
getwd()

stump = stump = "~/Library/CloudStorage/Box-Box/SerologyR01/Jiangsu"
```

```{r}
df = read_rds(paste0(stump, "/df_jiangsu.rds")) %>% 
  filter(barcode!="JS090")

mn = df %>% filter(neg==1) %>% 
  group_by(ag) %>% 
  summarise(mean_naive = mean(MFI),
            sd_naive = sd(MFI))

df = df %>% 
  left_join(mn) %>% 
  mutate(poscutoff = mean_naive + 2*sd_naive,
         seropos = ifelse(MFI>poscutoff, 1, 0)) 

breadth = df %>% 
  filter(neg==0) %>% 
  filter(ag != "Tetanus.toxoid") %>% 
  mutate(tsi = ifelse(neg==TRUE, 0, tsi)) %>% 
  group_by(barcode, tsi, neg) %>% 
  summarise(breadth = sum(seropos)) %>% 
  mutate(exposure_status = ifelse(neg==TRUE, "Naive control", "Exposed")) %>% 
  filter(!is.na(exposure_status)) %>% 
  left_join(df %>% select(barcode, tsicat) %>% distinct())

summary(breadth$breadth)
```

```{r}
ggplot(data=breadth %>% filter(neg==FALSE))+
  geom_point(aes(x=(as.numeric(tsi)), y=breadth))+
  scale_x_continuous(breaks = c(log(14), log(90), log(180), log(365), log(730)), labels=c(14, 90, 180, 365, 730))+
  theme_bw()+
  labs(x="Time Since Infection (days)")

ggplot(data=breadth %>% filter(neg==FALSE))+
  geom_point(aes(x=log(as.numeric(tsi)), y=breadth))+
  scale_x_continuous(breaks = c(log(14), log(90), log(180), log(365), log(730)), labels=c(14, 90, 180, 365, 730))+
  theme_bw()+
  labs(x="log Time Since Infection (days)")

```
make quintiles
```{r}
cut1 = 90
cut2 = 180
cut3 = 365
cut4 = 730
cut5 = 2027

baba = breadth %>% 
  ungroup() %>% 
  mutate(quint = ntile(tsi, 5),
         quintlabs = ifelse(quint==1, "0-35", 
                            ifelse(quint==2, "46-194",
                                   ifelse(quint==3, "194-532", 
                                          ifelse(quint==4, "549-1130",
                                                 ifelse(quint==5, "1163-2027", NA))))),
         quintlabs = factor(quintlabs, levels=c("0-35", "46-194", "194-532", "549-1130", "1163-2027")),
         tsicatlabs = ifelse(tsi>0 & tsi<=cut1, paste0("[0,", cut1, "]"),
                             ifelse(tsi>cut1 & tsi<=cut2, paste0("(", cut1, ",", cut2,"]"),
                                    ifelse(tsi>cut2 & tsi<=cut3, paste0("(", cut2, ",", cut3,"]"),
                                           ifelse(tsi>cut3 & tsi<=cut4, paste0("(", cut3, ",", cut4,"]"),
                                                  ifelse(tsi>cut4 & tsi<=cut5, paste0("(", cut4, ",", cut5,"]"), 
                                                         NA ))))),
         tsicatlabs = factor(tsicatlabs, levels = c(paste0("[0,", cut1, "]"), 
                                                    paste0("(", cut1, ",", cut2,"]"),
                                                    paste0("(", cut2, ",", cut3,"]"), 
                                                    paste0("(", cut3, ",", cut4,"]"),
                                                    paste0("(", cut4, ",", cut5,"]"),
                                                    NA))
         )
  


#quintranges = baba %>% 
#  group_by(quint) %>% 
#  summarise(min = min(days_return_sample),
#            max = max(days_return_sample),
#            medb = median(breadth),
#            quant = quantile(breadth, c(0.25, 0.5, 0.75)), 
#            q = c(0.25, 0.5, 0.75)) %>% 
#  pivot_wider(names_from = q, values_from = quant) %>% 
#  pivot_longer(c(`0.25`,`0.75`), names_to = "q", values_to = "quant" ) %>% 
#  rename(median = `0.5`)



ggplot(data=baba)+
  geom_boxplot(aes(x=as.factor(quint), y=breadth))+
  theme_bw()+
  labs(x="quintile")

ggplot(data=baba)+
  geom_boxplot(aes(x=as.factor(quintlabs), y=breadth))+
  theme_bw()+
  labs(x="Time Since Infection (days)")

ggplot(data=baba)+
  stat_summary(aes(x = quintlabs, y = breadth),
               fun.min = function(z) { quantile(z,0.25) },
               fun.max = function(z) { quantile(z,0.75) },
               fun = median,
               geom="errorbar",
               width=0.5)+
  stat_summary(aes(x = quintlabs, y = breadth),
               fun = median,
               geom="crossbar",
               width=0.5)+
  
  theme_bw()+
  geom_beeswarm(aes(x=quintlabs, y=breadth), col="lightseagreen")+
  labs(x="Time Since Infection (days)")


ggplot(data=baba)+
  stat_summary(aes(x = tsicatlabs, y = breadth),
               fun.min = function(z) { quantile(z,0.25) },
               fun.max = function(z) { quantile(z,0.75) },
               fun = median,
               geom="crossbar",
               width=0.5)+
  
  theme_bw()+
  geom_beeswarm(aes(x=tsicatlabs, y=breadth), col="lightseagreen")+
  labs(x="Time Since Infection (days)")

  
ggplot(data=baba %>% filter(!is.na(days_return_sample)))+
  geom_boxplot(aes(x=as.factor(quinttsi), y=breadth))+
  theme_bw()+
  labs(x="TSI Quintile")

ggplot(data=baba %>% filter(!is.na(days_return_sample)))+
  geom_boxplot(aes(x=tsicat, y=breadth))+
  theme_bw()

ggplot(data=baba %>% filter(!is.na(days_return_sample)))+
  geom_beeswarm(aes(x=tsicat, y=breadth))+
  geom_point(aes(x=tsicat, y=meanb), col='red')+
  theme_bw()+
  labs(x = "TSI category (days)")


```
```{r}
a1 = read_rds(paste0(stump, "/Jo paper/combos/a1.rds"))
```

