---
title: "R Notebook"
output: html_notebook
---

# Set up
```{r}
library(tidyverse)
library(ComplexHeatmap)
library(ggbeeswarm)
library(randomForest)
library(cvAUC)
library(ROCR)

set.seed(316)

rm(list=ls())
```


# Upload Data
```{r}
metadata = read_csv("https://raw.githubusercontent.com/jovinden/Jiangsu/refs/heads/main/data/metadata_jiangsu_vinden.csv")
# neg = TRUE if row represents a naive control sample
# id = unique participant id
# barcode = unique sample id (there are some cases of multiple samples from same id)
# sex
# age
# country = country where participant traveled and acquired malaria infection 
# country_cat = if country is in the top 5 most common countries, == country. else "other"
# date_abroad = date participant left china to go work abroad
# date_return = date participant returned to China 
# date_symp = date of symptom onset
# date_dx = date of malaria diagnosis
# date_sample = date of blood sample aquisition 
# tsi = time since infection (days between date_sample and date_return)

abdata = read_csv("https://raw.githubusercontent.com/jovinden/Jiangsu/refs/heads/main/data/abdata_jiangsu_vinden.csv")
# barcode = unique sample id
# ag = antigen on the luminex panel
# MFI = mean fluorescent intensity readout from luminex 



```

Add or calculate useful variables
```{r}
df = metadata %>%  
  #country_cat to simplify countries of travel (too many to plot at once)
  select(id, country) %>% distinct() %>% 
  group_by(country) %>% 
  summarise(n=n()) %>% 
  ungroup() %>% 
  mutate(rnk = rank(desc(n), ties.method = "first")) %>% 
  mutate(country_cat = as.factor(ifelse(rnk<6, country, "Other"))) %>% 
  select(country, country_cat) %>% 
  right_join(metadata) %>% 
  mutate(country_cat = factor(country_cat, levels = c("Angola", "Nigeria", "Equatorial Guinea", 
                                                      "Republic of Congo", "Guinea", "Other"))) %>% 
  left_join(abdata) %>% 
  filter(!is.na(MFI)) %>% #data not generated for JS040 
  # tsi = time since infection in days
  mutate(tsi = date_sample - date_dx) %>% 
  # tsicat = a categorical variable for tsi
  mutate(tsicat = ifelse(tsi<=90, "[0,90]", 
                         ifelse(tsi>90 & tsi<=180, "(90,180]", 
                                ifelse(tsi>180 & tsi<= 365, "(180, 365]",
                                       ifelse(tsi>365 & tsi <=730, "(365,730]", 
                                              ifelse(tsi>730, "(730,2027]", "bad")))))) %>% 
  mutate(tsicat = ifelse(neg==1, "Naive", tsicat)) %>% 
  mutate(tsicat = factor(tsicat, 
                         levels = c("[0,90]",  "(90,180]","(180, 365]", "(365,730]", "(730,2027]", "Naive" )))

# some plots will not need the naive controls. make a df without them for easy reference
df_noneg = df %>% filter(neg==FALSE)
```



# Table 1
```{r}
# number of participants 
n_participant = nrow(df_noneg %>% select(id) %>% distinct())
n_participant

# number of samples 
n_sample = nrow(df_noneg %>% select(barcode) %>% distinct())
n_sample
# number female
n_female = nrow(df_noneg %>% select(id, sex) %>% distinct() %>% filter(sex == "Female"))
n_female

# age dist 
summary(df_noneg %>% select(id, age) %>% distinct())

# time spent abroad 
ta = df_noneg %>% select(id, date_abroad, date_return) %>% distinct() %>% 
  mutate(days_abroad = as.numeric(date_return - date_abroad)) %>% 
  filter(!is.na(days_abroad))
summary(ta$days_abroad)

# tsi
summary(df_noneg %>% select(id, tsi) %>% distinct())

# country
summary(co %>% select(id, country_cat) %>% distinct())

```

# Table S1
```{r}
# country
summary(df_noneg %>% select(id, country) %>% distinct() %>% 
          mutate(country = as.factor(country)))
```


# Figure 1a Heatmap

```{r}
# order the ags from most reactive to least reactive with tt at the bottom
orderag = df %>% 
  select(barcode, ag, MFI, neg, tsi) %>% 
  group_by(ag) %>% 
  summarise(med_MFI = median(MFI)) %>% 
  mutate(med_MFI = ifelse(ag=="Tetanus_toxoid", 0, med_MFI),
         rnk = rank(desc(med_MFI)))

# generate a dataframe to feed to heatmap function
hdf = df %>% 
  select(barcode, ag, MFI, tsi) %>% 
  mutate(logMFI = log(MFI)) %>% 
  arrange(tsi) %>% 
  select(-tsi, -MFI) %>% 
  pivot_wider(names_from = "barcode", values_from = "logMFI") %>% 
  left_join(orderag %>% select(ag, rnk)) %>% 
  mutate(ag = fct_reorder(ag, rnk)) %>% 
  arrange(ag) %>% 
  select(-rnk) %>% 
  column_to_rownames("ag")

# exposure status matrix for annotating heatmap
exp_ma = df %>% 
  select(barcode, tsi, neg) %>% distinct() %>% 
  mutate(tsicat = ifelse(is.na(tsi), "Naive control", 
                         ifelse(tsi<=90, "0-3 months",
                          ifelse(tsi>90&tsi<=180, "3-6 months", 
                                ifelse(tsi>180&tsi<=365, "6-12 months", 
                                       ifelse(tsi>365&tsi<=730, "1-2 years",
                                              ifelse(tsi>730, "2+ years", "wurt"))))))) %>% 
  arrange(tsi)

# generate annotation object
tsicat = HeatmapAnnotation(TSI = as.matrix(exp_ma$tsicat),
                           col = list(TSI = c("0-3 months" ="#f0f9e8",
                                   "3-6 months" = "#bae4bc", 
                                  "6-12 months" = "#7bccc4", 
                                   "1-2 years" = "#43a2ca",
                                   "2+ years"  = "#0868ac", 
                                   "Naive control" =  "#969696")),
                           annotation_legend_param = list(TSI = list(nrow = 1)))

# assemble heatmap
a = Heatmap(as.matrix(hdf), cluster_rows = FALSE, cluster_columns = FALSE, top_annotation = c(tsicat),
        show_column_names = FALSE,
        name = "log(MFI)",
        heatmap_legend_param = list(direction = "horizontal"))

# draw heatmap
draw(a, merge_legend = TRUE, heatmap_legend_side = "bottom", 
    annotation_legend_side = "bottom")


```


# Figure 2a
```{r}
# calculate mean MFI of naive samples 
mn = df %>% filter(neg==1) %>% 
  group_by(ag) %>%        
  summarise(mean_naive = mean(MFI),
            sd_naive = sd(MFI))

ggplot()+
  theme_bw()+
  geom_point(data = df_noneg, aes(x=log(as.numeric(tsi)), y=log(MFI), col=country_cat), size=1)+
  scale_x_continuous(breaks = c(log(14), log(90), log(180), log(365), log(730)), 
                     labels=c(14, 90, 180, 365, 730))+
  geom_hline(data=mn, aes(yintercept = log(mean_naive)))+
  facet_wrap(~ag)+
  scale_color_brewer(palette = "Set2")+
  theme(axis.text.x = element_text(angle = 90, vjust = 1, hjust=1, size=6))+
  labs(x="Time Since Infection (days)",
       col = "Country of Travel")
```
# Figure 2b breadth vs TSI
```{r}
# calculate breadth of each sample
breadth = df_noneg %>% 
  left_join(mn) %>% 
  # define seropositive if MFI > than 3sd above mean of Naive controls
  mutate(seropos = ifelse(MFI > mean_naive + 3*sd_naive, 1, 0)) %>% 
  filter(ag!="Tetanus_toxoid") %>% 
  group_by(barcode, tsicat) %>% 
  summarise(breadth = sum(seropos)) 

ggplot(data=breadth)+
  stat_summary(aes(x = tsicat, y = breadth),
               fun.min = function(z) { quantile(z,0.25) },
               fun.max = function(z) { quantile(z,0.75) },
               fun = median,
               geom="crossbar",
               width=0.5)+
  
  theme_test()+
  geom_beeswarm(aes(x=tsicat, y=breadth), col="lightseagreen")+
  labs(x="Time Since Infection (days)")
```
Figure 2c mean MFI vs tsi
```{r}
meanMFI = df %>% 
  filter(ag!="Tetanus_toxoid") %>% 
  group_by(barcode, tsicat) %>% 
  summarise(mean_MFI = mean(MFI))

ggplot(data=meanMFI)+
  stat_summary(aes(x = tsicat, y = mean_MFI),
               fun.min = function(z) { quantile(z,0.25) },
               fun.max = function(z) { quantile(z,0.75) },
               fun = median,
               geom="crossbar",
               width=0.5)+
  theme_test()+
  geom_beeswarm(aes(x=tsicat, y=mean_MFI), col="#fc8d62")+
  labs(x="Time Since Infection (days)",
       y = "mean MFI of sample")
```
# Figure 3 ROC single ag cutoffs

First, set up some functions for running cross-validated random forests. 

## cvFolds
```{r}
# splits data into V folds, balanced by outcome. 
cvFolds = function(Y, V){ #Y = outcome, #V = number of folds
  Y0 = split(sample(which(Y==FALSE)), rep(1:V, length = length(which(Y==FALSE))))
  Y1 = split(sample(which(Y==TRUE)), rep(1:V, length = length(which(Y==TRUE))))
  folds = vector("list", length=V)
  for (v in seq(V)) {folds[[v]] = c(Y0[[v]], Y1[[v]])}
  return(folds)
}
```

## doFit
```{r}
# Train random forest model to V-1 folds, predict on remaining fold. 
doFit <- function(v, folds, data){ 
  
  fit <- randomForest(as.factor(outcome)~., data = data[-folds[[v]],], type="prob")
  
  pred <- predict(fit, newdata = data[folds[[v]],], type = "prob")
  return(pred[,2])
}
```

## xval_rf_fxn
```{r}

xval_rf_fxn = function(fdf, V=5, out = 180){
  # fdf = function data frame. Requires barcode, ag, MFI, tsi. 
  # V = # of folds for x-validation
  # out = cutoff for the outcome variable in days (predicting exposure in the past x days, x = out) 
  
  # generate a df that is properly formatted for feeding to rf 
  rdf = fdf %>% 
    # generate binary outcome variable - was individual exposed in previous (out) days?
    mutate(outcome = ifelse(tsi<=out, TRUE, FALSE)) %>% 
    select(barcode, ag, MFI, outcome) %>% distinct() %>% # select predictor and outcome variables
    filter(!is.na(outcome)) %>% 
    pivot_wider(names_from = ag, values_from = MFI) %>% # format so each ag is a separate predictor var
    select(-barcode) # I only remove barcode at the very last step so that i can check ordering easily
  
  # use cvFolds to generate folds
  folds = cvFolds(Y = rdf$outcome, V = V) # create V folds
  
  # run dofit on all the folds
  predictions <- unlist(sapply(seq(V), doFit, folds = folds, data = rdf)) #CV train/predict
  
  predictions[unlist(folds)] <- predictions #Re-order pred values
  
  # Get CV AUC and confidence interval
  res <- cvAUC(predictions = predictions, labels = rdf$outcome, folds = folds) 
  ci.res <- ci.cvAUC(predictions = predictions, labels = rdf$outcome, folds = folds) 
  
  # retrieve ROC plotting data for all folds
  flist = list()
  for(i in seq(V)){
    a = as_tibble(res$perf@x.values[[i]]) %>% 
      rename(fpr = value) %>% 
      mutate(tpr = res$perf@y.values[[i]],
             fold = as.character(i),
             auc = res$fold.AUC[i],
             cvauc_se = NA,
             cvauc_ci_low = NA,
             cvauc_ci_high = NA,
             sens95 = NA,
             sens95_ci_low = NA,
             sens95_ci_high = NA)
    
    flist[[i]] = a
  }
  
  # now get an overall ROC curve and measure sens and spec
  overall_pred = prediction(predictions, rdf$outcome)
  overall_perf = performance(overall_pred, "tpr", "fpr")
  overall_auc = performance(overall_pred, "auc")
  overall_sens_spec = performance(overall_pred, "sens", "spec")
  
  library(pROC)
  ci.out <- ci.cvAUC(predictions = predictions, labels = rdf$outcome, folds = folds) 
  sensci = ci.se(rdf$outcome, predictions, specificities = (0.95))
  
  # find sens at 90, 95, 98$ spec
  
  b = as_tibble(overall_perf@x.values[[1]]) %>% 
      rename(fpr = value) %>% 
      mutate(tpr = overall_perf@y.values[[1]],
             fold = "all",
             spec = overall_sens_spec@x.values[[1]],
             sens = overall_sens_spec@y.values[[1]],
             auc = ci.out$cvAUC,
             cvauc_se = ci.out$se,
             cvauc_ci_low = ci.out$ci[1],
             cvauc_ci_high = ci.out$ci[2],
             sens95 = sensci[2],
             sens95_ci_low = sensci[1],
             sens95_ci_high = sensci[3])
  
  allresults = bind_rows(flist) %>% 
    bind_rows(b)
}
  
```


```{r}
aa = xval_rf_fxn(df)
```

